[theme]
primaryColor="#F63366"  # Example primary color (optional)
backgroundColor="#FFFFFF"  # Set background to white
secondaryBackgroundColor="#F0F2F6"  # Example secondary background (optional)
textColor="#000000"   # Set text color to black
font="sans serif"  # Example font (optional)
